services:
  gateway:
    image: nginx:alpine
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - user
      - social
      - workout

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    restart: always
    env_file: .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/init-database.sql:/docker-entrypoint-initdb.d/init-database.sql

  user:
    build: ./userService
    env_file: ./.env
    depends_on:
      - postgres
      - rabbitmq
    restart: always

  social:
    build: ./socialService
    env_file:
      - ./.env
    depends_on:
      - postgres
      - rabbitmq

  workout:
    build: ./workoutService
    env_file: ./.env
    depends_on:
      - postgres
      - rabbitmq
    restart: always


volumes:
  postgres_data:
  rabbitmq_data: